---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mqtt-data-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: {{mqtt_storage}}