---
apiVersion: v1
kind: Service
metadata:
  name: mqtt-service
spec:
  selector:
    app: mqtt
  type: NodePort
  ports:
  - name: mqtt
    nodePort: {{mqtt_port}}
    port: 1883
    protocol: TCP
    targetPort: mqtt




