---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt
  labels:
    app: mqtt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqtt
  template:
    metadata:
      labels:
        app: mqtt
    spec:
      containers:
      - name: mqtt
        image: {{mqtt_image}}
        ports:
        - containerPort: 1883
          name: mqtt
          protocol: TCP
        - containerPort: 9090
          name: websocket
          protocol: TCP
        volumeMounts:
        - name: mqtt-config
          mountPath: /mosquitto/config
        - name: mqtt-data
          mountPath: /mosquitto/data
      volumes:
      - name: mqtt-data
        persistentVolumeClaim:
          claimName: mqtt-data-claim
      - name: mqtt-config
        configMap:
          defaultMode: 420
          name: mqtt-config